### ISSUE TITLE
FastAI V1 Documentation linking to FastAI V2 Code

### ISSUE THREAD

**Issue by TannerGilbert** [fastai/fastai1#3]
The [FastAI V1 documentation](https://fastai1.fast.ai/dev/index.html) links to FastAI V2 because when moving the documentation from docs.fast.ai to fastai1.fast.ai and moving the code from fastai/fastai to fastai/fastai1 these links weren't edited.

**Comment by bjrne** [comment]
Unfortunately this is still the case for the search function, is there any possibility to change this? This is really unfortunate when you have to look up old APIs... It just shows results for the new page.
